---

name: lint

on: [workflow_call]  # allow this workflow to be called from other workflows

env:
  PYTHON_VERSION: 3.9

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Check python linting
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start linter
        run: |
          docker run --rm -w="/code/{{ cookiecutter.backend_container_name }}" -v $(pwd):/code alpine/flake8:5.0.4 .

  black:
    runs-on: ubuntu-latest
    name: Black code formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        {% raw %}
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        {% endraw %}
      - name: run black
        working-directory: ./{{ cookiecutter.backend_container_name }}
        run: |
          pip install black==22.6.0
          black --check .

  isort:
    runs-on: ubuntu-latest
    name: isort imports
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        {% raw %}
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        {% endraw %}
      - name: run black
        working-directory: ./{{ cookiecutter.backend_container_name }}
        run: |
          pip install isort==5.12.0
          isort src
