---

name: pull-request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  unit-tests:
    needs: [lint]
    uses: ./.github/workflows/unit-tests.yml
