default_language_version:
    python: python{{ cookiecutter.py_version }}

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: ["--config=./{{ cookiecutter.backend_container_name }}/pyproject.toml"]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.241'
    hooks:
        - id: ruff
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--settings-path=./{{ cookiecutter.backend_container_name }}/pyproject.toml"]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.982
#     hooks:
#       - id: mypy
#         args: ["--config-file=./{{ cookiecutter.backend_container_name }}/pyproject.toml"]
