name: pre-commit and tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  pre-commit:
    runs-on: ubuntu-latest
    name: Check python linting
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
